# Generated by Django 3.0.6 on 2020-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=10000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
