# Generated by Django 3.0.6 on 2020-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='about',
            field=models.CharField(max_length=10000),
        ),
    ]
