# Generated by Django 3.0.6 on 2020-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='bandcamp_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_player_url',
            field=models.URLField(unique=True),
        ),
    ]
